services:
  - type: web
    name: asim-vokshi-website
    runtime: static
    buildCommand: pnpm install --frozen-lockfile && pnpm build
    staticPublishPath: ./dist/public
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
